services:
  llm-chat:
    container_name: llm-chat
    build:
      dockerfile: Dockerfile.llm
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
    - "3019:3019"
    networks:
      - bmms-network

  ui-src:
    image: 0xt4i/ui
    container_name: ui-service 
    ports:
      - "5173:5173"
    env_file: ./docker-retail.env
    networks:
      - bmms-network
    depends_on:
      auth-src:
        condition: service_started

  auth-src:
    container_name: auth-service
    build:
      dockerfile: Dockerfile.auth
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bmms-network

  api-gateway:
    container_name: api-gateway
    build:
      dockerfile: Dockerfile.api
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bmms-network

  crm-src:
    container_name: crm-service
    build:
      dockerfile: Dockerfile.crm
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bmms-network
    depends_on:
      crm-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  customer-src:
    container_name: customer-service
    build:
      dockerfile: Dockerfile.inventory
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bmms-network
    depends_on:
      customer-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  catalogue-src:
    container_name: catalogue-service
    build:
      dockerfile: Dockerfile.catalogue
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bmms-network
    depends_on:
      catalogue-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  inventory-src:
    container_name: inventory-service
    build:
      dockerfile: Dockerfile.inventory
      context: ./bmms
    env_file: ./docker-retail.env
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bmms-network
    depends_on:
      inventory-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  order-src:
    container_name: order-service
    build:
      dockerfile: Dockerfile.order
      context: ./bmms
    env_file: ./docker-retail.env
    networks:
      - bmms-network
    depends_on:
      order-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  payment-src:
    container_name: payment-service
    build:
      dockerfile: Dockerfile.payment
      context: ./bmms
    env_file: ./docker-retail.env
    networks:
      - bmms-network
    depends_on:
      payment-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  billing-src:
    container_name: billing-service
    build:
      dockerfile: Dockerfile.billing
      context: ./bmms
    env_file: ./docker-retail.env
    networks:
      - bmms-network
    depends_on:
      billing-db:
        condition: service_healthy
      redpanda-0:
        condition: service_healthy 

  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=order_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - order_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s      
    networks:
      - bmms-network

  billing-db:
    image: mysql:8.0
    container_name: billing-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=billing_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - billing_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - bmms-network

  payment-db:
    image: mysql:8.0
    container_name: payment-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=payment_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - payment_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - bmms-network

  customer-db:
    image: mysql:8.0
    container_name: customer-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=customer_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - customer_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bmms-network

  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=inventory_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - inventory_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bmms-network
  
  crm-db:
    image: mysql:8.0
    container_name: crm-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=crm_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - crm_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bmms-network

  catalogue-db:
    image: mysql:8.0
    container_name: catalogue-db
    restart: unless-stopped
    env_file: ./docker-retail.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=catalogue_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - catalogue_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bmms-network

  redpanda-0:
    image: redpandadata/redpanda:v25.1.12
    container_name: redpanda-0
    command:
      - redpanda start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda-0:29092,OUTSIDE://localhost:9092
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9644:9644"
    healthcheck:
      test: ["CMD", "bash", "-c", "rpk cluster info --brokers localhost:29092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - redpanda_0_data:/var/lib/redpanda/data
    networks:
      - bmms-network
networks:
  bmms-network:
    driver: bridge

volumes:
  customer_db_data:
  crm_db_data:
  catalogue_db_data:
  order_db_data:
  billing_db_data:
  payment_db_data:
  inventory_db_data:
  redpanda_0_data: